const kanjiDict = {
  "一緒": { Pron:"いっしょ", Mean:"together", Ex:"私たちは一緒に映画を見に行きました。" },
  "二人": { Pron:"ふたり", Mean:"two people", Ex:"二人で映画を見に行きました。" },
  "人": { Pron:"ひと", Mean:"person, human", Ex:"あの人は先生です。" },
  "今": { Pron:"いま", Mean:"now", Ex:"今、勉強しています。" },
  "住": { Pron:"すむ", Mean:"to live; to reside", Ex:"私は東京に住んでいます。" },
  "働": { Pron:"はたらく", Mean:"to work", Ex:"彼は毎日会社で働いています。" },
  "優": { Pron:"やさしい", Mean:"gentle; kind", Ex:"彼は優しい人です。" },
  "児童教育": { Pron:"じどうきょういく", Mean:"child education", Ex:"児童教育は子どもの成長に重要です。" },
  "出身": { Pron:"しゅっしん", Mean:"hometown; origin", Ex:"彼は東京出身です。" },
  "勉強": { Pron:"べんきょう", Mean:"study", Ex:"毎日日本語を勉強します。" },
  "勉強中": { Pron:"べんきょうちゅう", Mean:"studying", Ex:"今は勉強中です。" },
  "取": { Pron:"とる", Mean:"to take", Ex:"りんごを取ります。" },
  "問題": { Pron:"もんだい", Mean:"problem; question", Ex:"この問題は難しいです。" },
  "喜": { Pron:"よろこぶ", Mean:"to be pleased", Ex:"彼は合格を喜びました。" },
  "地域": { Pron:"ちいき", Mean:"region; area", Ex:"この地域は自然が豊かです。" },
  "増": { Pron:"ふえる", Mean:"to increase", Ex:"人口が増えています。" },
  "大事": { Pron:"だいじ", Mean:"important", Ex:"健康は大事です。" },
  "大切": { Pron:"たいせつ", Mean:"important; precious", Ex:"家族はとても大切です。" },
  "夫": { Pron:"おっと", Mean:"husband", Ex:"彼は私の夫です." },
  "始": { Pron:"はじめる", Mean:"to begin", Ex:"新しい仕事を始めます。" },
  "子": { Pron:"こ", Mean:"child", Ex:"子どもが公園で遊んでいます。" },
  "学校": { Pron:"がっこう", Mean:"school", Ex:"私は毎日学校に行きます。" },
  "安心": { Pron:"あんしん", Mean:"relief; peace of mind", Ex:"家族が元気だと安心します。" },
  "家族": { Pron:"かぞく", Mean:"family", Ex:"私の家族は四人です。" },
  "寄": { Pron:"よる", Mean:"to stop by", Ex:"駅に寄ってから帰ります。" },
  "小山市": { Pron:"おやまし", Mean:"Oyama City", Ex:"ここは小山市です。" },
  "少": { Pron:"すこし", Mean:"a little", Ex:"少し疲れています。" },
  "強": { Pron:"つよい", Mean:"strong", Ex:"彼はとても強いです。" },
  "心": { Pron:"こころ", Mean:"heart; mind", Ex:"彼は優しい心を持っています。" },
  "思": { Pron:"おもう", Mean:"to think", Ex:"私はそう思います。" },
  "感": { Pron:"かんじょう", Mean:"feeling; emotion", Ex:"強い感情を持っています。" },
  "慣": { Pron:"なれる", Mean:"to get used to", Ex:"新しい環境に慣れました。" },
  "戸惑": { Pron:"とまどう", Mean:"to be confused", Ex:"新しい環境に戸惑いました。" },
  "手伝う": { Pron:"てつだう", Mean:"to help", Ex:"友達の引っ越しを手伝いました。" },
  "持つ": { Pron:"もつ", Mean:"to hold; carry", Ex:"かばんを持っています。" },
  "接": { Pron:"せっする", Mean:"to deal with", Ex:"丁寧に接しました。" },
  "教": { Pron:"おしえる", Mean:"to teach", Ex:"先生が日本語を教えます。" },
  "教育": { Pron:"きょういく", Mean:"education", Ex:"教育は大切です。" },
  "方": { Pron:"ほう", Mean:"way; direction", Ex:"こちらの方がいいです。" },
  "日常会話": { Pron:"にちじょうかいわ", Mean:"daily conversation", Ex:"日常会話を練習します。" },
  "日本": { Pron:"にほん", Mean:"Japan", Ex:"日本には四季があります。" },
  "日本語": { Pron:"にほんご", Mean:"Japanese language", Ex:"私は日本語を勉強しています。" },
  "日本語教室": { Pron:"にほんごきょうしつ", Mean:"Japanese class", Ex:"日本語教室で学びます。" },
  "日本語能力試験": { Pron:"にほんごのうりょくしけん", Mean:"JLPT", Ex:"日本語能力試験に合格したいです。" },
  "暮": { Pron:"くらす", Mean:"to live", Ex:"家族と一緒に暮らしています。" },
  "最初": { Pron:"さいしょ", Mean:"first", Ex:"最初に自己紹介してください。" },
  "最後": { Pron:"さいご", Mean:"last", Ex:"最後の問題は難しかったです。" },
  "本日": { Pron:"ほんじつ", Mean:"today", Ex:"本日は晴れです。" },
  "楽": { Pron:"らく", Mean:"easy; comfortable", Ex:"この仕事は楽です。" },
  "母": { Pron:"はは", Mean:"mother", Ex:"母は毎日料理を作ります。" },
  "添": { Pron:"そえる", Mean:"to attach", Ex:"手紙に写真を添えました。" },
  "温": { Pron:"おん", Mean:"warmth; temperature", Ex:"温度がちょうどいいです。" },
  "現在": { Pron:"げんざい", Mean:"current", Ex:"現在、日本語を勉強しています。" },
  "環境": { Pron:"かんきょう", Mean:"environment", Ex:"環境を守ることは大切です。" },
  "生活": { Pron:"せいかつ", Mean:"life; living", Ex:"毎日の生活を大切にしましょう。" },
  "申": { Pron:"もうす", Mean:"to say humbly", Ex:"私は山田と申します。" },
  "目指": { Pron:"めざす", Mean:"to aim for", Ex:"医者を目指しています。" },
  "着": { Pron:"きる", Mean:"to wear", Ex:"新しい服を着ます。" },
  "程度": { Pron:"ていど", Mean:"degree; level", Ex:"中級程度の日本語です。" },
  "簡単": { Pron:"かんたん", Mean:"easy", Ex:"この問題は簡単です。" },
  "結婚": { Pron:"けっこん", Mean:"marriage", Ex:"来月結婚します。" },
  "考": { Pron:"かんがえる", Mean:"to think", Ex:"将来について考えます。" },
  "自己紹介": { Pron:"じこしょうかい", Mean:"self-introduction", Ex:"自己紹介をします。" },
  "苦手": { Pron:"にがて", Mean:"not good at", Ex:"数学が苦手です。" },
  "英語": { Pron:"えいご", Mean:"English", Ex:"英語を勉強しています。" },
  "英語教師助手": { Pron:"えいごきょうしじょしゅ", Mean:"English teacher assistant", Ex:"英語教師助手として働いています。" },
  "落": { Pron:"おちる", Mean:"to fall", Ex:"葉が落ちます。" },
  "落ち着いている": { Pron:"おちついている", Mean:"calm", Ex:"彼女は落ち着いています。" },
  "通う": { Pron:"かよう", Mean:"to commute; attend", Ex:"毎日学校に通います。" },
  "間違": { Pron:"まちがい", Mean:"mistake", Ex:"この文には間違いがあります。" },
  "関心": { Pron:"かんしん", Mean:"interest", Ex:"環境問題に関心があります。" },
  "面接": { Pron:"めんせつ", Mean:"interview", Ex:"明日面接があります。" },
  "願": { Pron:"ねが(う)", Mean:"to wish", Ex:"成功を願っています。" },

  "病院": { Pron:"びょういん", Mean:"hospital", Ex:"病院へ行きました。" },
  "整形外科": { Pron:"せいけいげか", Mean:"orthopedics", Ex:"整形外科を受診します。" },
  "受付": { Pron:"うけつけ", Mean:"reception", Ex:"受付で保険証を出してください。" },
  "初診": { Pron:"しょしん", Mean:"first visit", Ex:"今日は初診です。" },
  "再診": { Pron:"さいしん", Mean:"follow-up visit", Ex:"再診に来る/come back for a follow-up" },
  "患者": { Pron:"かんじゃ", Mean:"patient", Ex:"患者さんはこちらです。" },
  "診察": { Pron:"しんさつ", Mean:"medical examination", Ex:"これから診察です。" },
  "受診": { Pron:"じゅしん", Mean:"medical consultation", Ex:"腰痛で受診しました。" },
  "医師": { Pron:"いし", Mean:"doctor", Ex:"医師が説明します。" },
  "先生": { Pron:"せんせい", Mean:"doctor; teacher", Ex:"先生に相談してください。" },
  "看護師": { Pron:"かんごし", Mean:"nurse", Ex:"看護師が血圧を測ります。" },
  "症状": { Pron:"しょうじょう", Mean:"symptom", Ex:"症状を教えてください。" },
  "腰痛": { Pron:"ようつう", Mean:"lower back pain", Ex:"腰痛が続いています。" },
  "腰": { Pron:"こし", Mean:"lower back", Ex:"腰が痛いです。" },
  "痛": { Pron:"いた（い）", Mean:"painful", Ex:"歩くと痛いです。" },
  "痛み": { Pron:"いたみ", Mean:"pain", Ex:"痛みはありますか。" },
  "肩": { Pron:"かた", Mean:"shoulder", Ex:"肩も痛いです。" },
  "首": { Pron:"くび", Mean:"neck", Ex:"首が回りません。" },
  "膝": { Pron:"ひざ", Mean:"knee", Ex:"膝が痛いです。" },
  "足": { Pron:"あし", Mean:"leg; foot", Ex:"足がしびれます。" },
  "腕": { Pron:"うで", Mean:"arm", Ex:"腕が上がりません。" },
  "背中": { Pron:"せなか", Mean:"back", Ex:"背中が張っています。" },
  "治療": { Pron:"ちりょう", Mean:"treatment", Ex:"治療を始めます。" },
  "検査": { Pron:"けんさ", Mean:"test", Ex:"検査をします。" },
  "診断": { Pron:"しんだん", Mean:"diagnosis", Ex:"診断結果を聞きました。" },
  "問診": { Pron:"もんしん", Mean:"medical interview", Ex:"問診があります。" },
  "問診票": { Pron:"もんしんひょう", Mean:"questionnaire form", Ex:"問診票を書いてください。" },
  "記入": { Pron:"きにゅう", Mean:"fill in", Ex:"ここに記入してください。" },
  "名前": { Pron:"なまえ", Mean:"name", Ex:"お名前をどうぞ。" },
  "住所": { Pron:"じゅうしょ", Mean:"address", Ex:"住所を書いてください。" },
  "予約": { Pron:"よやく", Mean:"appointment", Ex:"予約はありますか。" },
  "会計": { Pron:"かいけい", Mean:"payment", Ex:"会計はこちらです。" },
  "薬": { Pron:"くすり", Mean:"medicine", Ex:"薬を出します。" },
  "湿布": { Pron:"しっぷ", Mean:"medicated patch", Ex:"湿布を貼ってください。" },
  "痛み止め": { Pron:"いたみどめ", Mean:"painkiller", Ex:"痛み止めを処方します。" },
  "処方": { Pron:"しょほう", Mean:"prescription", Ex:"薬を処方します。" },
  "処方箋": { Pron:"しょほうせん", Mean:"prescription form", Ex:"処方箋を薬局へ持って行ってください。" },
  "薬局": { Pron:"やっきょく", Mean:"pharmacy", Ex:"薬局で薬を受け取れます。" },
  "安静": { Pron:"あんせい", Mean:"rest", Ex:"数日は安静にしてください。" },
  "運動": { Pron:"うんどう", Mean:"exercise", Ex:"軽い運動をしましょう。" },
  "歩行": { Pron:"ほこう", Mean:"walking", Ex:"歩行時に痛みがあります。" },
  "立つ": { Pron:"たつ", Mean:"to stand", Ex:"長く立つと痛いです。" },
  "座る": { Pron:"すわる", Mean:"to sit", Ex:"座ると楽です。" },
  "寝る": { Pron:"ねる", Mean:"to lie down; sleep", Ex:"寝る時も痛いです。" },
  "動く": { Pron:"うごく", Mean:"to move", Ex:"急に動くと痛いです。" },
  "曲げる": { Pron:"まげる", Mean:"to bend", Ex:"腰を曲げると痛いです。" },
  "伸ばす": { Pron:"のばす", Mean:"to stretch", Ex:"足を伸ばしてください。" },
  "歩": { Pron:"あるく", Mean:"to walk", Ex:"歩くと痛みます。" },
  "転倒": { Pron:"てんとう", Mean:"fall down", Ex:"昨日転倒しました。" },
  "事故": { Pron:"じこ", Mean:"accident", Ex:"事故のあと痛みます。" },
  "仕事": { Pron:"しごと", Mean:"work", Ex:"仕事で重い物を持ちました。" },
  "重い": { Pron:"おもい", Mean:"heavy", Ex:"重い荷物を持ちました。" },
  "荷物": { Pron:"にもつ", Mean:"baggage", Ex:"荷物を持ったあと痛くなりました。" },
  "右": { Pron:"みぎ", Mean:"right", Ex:"右の腰が痛いです。" },
  "左": { Pron:"ひだり", Mean:"left", Ex:"左足がしびれます。" },
  "前": { Pron:"まえ", Mean:"front; before", Ex:"前かがみで痛いです。" },
  "後ろ": { Pron:"うしろ", Mean:"back; behind", Ex:"後ろへ反ると痛いです。" },
  "今日": { Pron:"きょう", Mean:"today", Ex:"今日は診察の日です。" },
  "昨日": { Pron:"きのう", Mean:"yesterday", Ex:"昨日から痛いです。" },
  "明日": { Pron:"あした", Mean:"tomorrow", Ex:"明日また来てください。" },
  "週間": { Pron:"しゅうかん", Mean:"week", Ex:"一週間痛みがあります。" },
  "時間": { Pron:"じかん", Mean:"time; hour", Ex:"長時間座ると痛いです。" },
  "大丈夫": { Pron:"だいじょうぶ", Mean:"no problem", Ex:"大丈夫心配しないでください。" },
  "現時点": { Pron:"げんじてん", Mean:"at present", Ex:"現時点では異常ありません。" },
  "検査室": { Pron:"けんさしつ", Mean:"examination room", Ex:"検査室で検査します。" },
  "腫瘍": { Pron:"しゅよう", Mean:"tumor", Ex:"腫瘍があると診断される。" },
  "部分": { Pron:"ぶぶん", Mean:"part", Ex:"それはいろいろな部分からできている" },
  "約半年前": { Pron:"やくはんとしまえ", Mean:"about 6 months ago", Ex:"それは約半年前の出来事です" },
  "工場": { Pron:"こうじょう", Mean:"factory", Ex:"わたしはこの工場で働いています" },
  "保険証": { Pron:"ほけんしょう", Mean:"insurance certificate", Ex:"受付で健康保険証をていしゅつする" },
  "書": { Pron:"か（く）", Mean:"write", Ex:"文字を書く" },
  "手伝": { Pron:"てつだ（う）", Mean:"assist/support", Ex:"仕事を手伝う" },
  "初": { Pron:"はじ（めて）", Mean:"first time", Ex:"初めてきました" },
  "或": { Pron:"ある（いは）", Mean:"or", Ex:"A 或いは B、A or B" },
  "上手": { Pron:"じょうず", Mean:"superior,good", Ex:"上手な使い方,good use [usage]" },
  "運": { Pron:"はこ（ぶ）", Mean:"convey,carry ,transport", Ex:"荷物を運ぶ" },
  "重": { Pron:"おも（い）", Mean:"heavy,", Ex:"重いものをもち上げる" },
  "立": { Pron:"た（つ）", Mean:"stand,", Ex:"立ちあがる、stand up" },
  "座": { Pron:"すわ（る）", Mean:"sit down", Ex:"座る場所、a place to sit (down)" },
  "調": { Pron:"しら（べる）", Mean:"consult、examine,check", Ex:"～かどうかを調べる,check (to see) whether (or not)" },
  "心配": { Pron:"しんぱい（する）", Mean:"worry,anxious", Ex:"～のことを心配している,anxious about" },
  "詳": { Pron:"くわ（しい）", Mean:"detail", Ex:"詳しいことはわからない、I don't know the full detail" },
  "強": { Pron:"つよ（い）", Mean:"strong,hard,powerful", Ex:"強いアルコールのみもの、a strong alcoholic drink" },
  "長": { Pron:"なが（い）", Mean:"long", Ex:"長く立っていると～、standing for a long time" },
  "力": { Pron:"ちから", Mean:"force,strength", Ex:"力をいれる、put strength" },
  "排便": { Pron:"はいべん", Mean:"empty one's bowels,evacuate the [one's] bowels", Ex:"排便の頻度,frequency of bowel movement" }, 
  "普通": { Pron:"ふつう", Mean:"normal,usual,common", Ex:"普通ではないじょうたい,unusual situation" }, 
  "感染": { Pron:"かんせん", Mean:"infection", Ex:"感染が疑われる患者、patient with suspected infection" }, 
  "排尿": { Pron:"はいにょう", Mean:"urination", Ex:"排尿の切れが悪いこと,difficulty in starting or stopping urination" }, 
  "手続": { Pron:"てつづ(き)", Mean:" registering", Ex:"手続きする前に、before registering" }, 
  "手術": { Pron:"しゅじゅつ", Mean:" operation,surgery", Ex:"手術が必要である、require surgery" }, 
  "必要": { Pron:"ひつよう", Mean:" necessity,need", Ex:"必要がない、have no use" },  
  "結果": { Pron:"けっか", Mean:" result", Ex:"結果から学ぶ、learn from the results" },  
  "多": { Pron:"おお（くは）", Mean:" much of", Ex:"責任の多くは～にある、much of the blame lies with" },  
  "治": { Pron:"なお（る）", Mean:"get well,recover from", Ex:"治る可能性がかなりある、have a good chance of being cured" },  
  "後": { Pron:"あと", Mean:"get well,recover from", Ex:"この後、after this" }, 
  "見": { Pron:"み（る）", Mean:"look at", Ex:"結果を見る、look at results" },
  "本当": { Pron:"ほんとう", Mean:" really", Ex:"本当なの？、Oh, really?" },
  "椎間板": { Pron:"ついかんばん", Mean:" disk,disc", Ex:"椎間板ヘルニア/disc [disk] herniation [hernia]" },
  "行": { Pron:"おこな（う）", Mean:" to do,conduct", Ex:"行うべき唯一のこと/only thing to do" },
  "重大": { Pron:"じゅうだい", Mean:" importance,significance", Ex:"重大ではない犯罪,/an insignificant crime" },
  "通訳": { Pron:"つうやく", Mean:" translation,interpretation ", Ex:"通訳がいないと何も分からない/not understand a thing without an interpreter" },
  "状態": { Pron:"じゅうたい", Mean:" condition,situation", Ex:"状態を確認する/check for a condition" },
  "後": { Pron:"あと", Mean:" after", Ex:"この後すぐに/right after this" },
  "悪化": { Pron:"あっか", Mean:" complicate,worsen", Ex:"病気を悪化させる/complicate a disease" },
  "精密検査": { Pron:"せいみつけんさ", Mean:" complete checkup,detailed examination", Ex:"精密検査を受ける/have a detailed examination" },
  "筋肉": { Pron:"きんにく", Mean:" muscle", Ex:"筋肉がほぐれるのを感じる/feel one's muscle relax" },
  "姿勢": { Pron:"しせい", Mean:" posture,position", Ex:"姿勢が悪い/have a bad posture" },
  "自然": { Pron:"しぜん（に）", Mean:" naturally,by itself", Ex:"自然になくなる/disappear by itself" },
  "改善": { Pron:"かいぜん（する）", Mean:" get out from under,make improvements", Ex:"～する方法を改善する/improve ways to" },
  "病気": { Pron:"びょうき", Mean:"disease,illness", Ex:"病気からの回復する/recover from one's disease" },
  "可能性": { Pron:"かのうせい", Mean:"possibility,capability", Ex:"可能性がある/have possibilities" },
  "別": { Pron:"べつ（の）", Mean:"different,alternative,another", Ex:"別のやり方で/in a different way" },
  "原因": { Pron:"げんいん", Mean:"cause,reason", Ex:"原因がウイルスの場合/when the cause is a virus" },
  "力仕事": { Pron:"ちからしごと", Mean:"heavy lifting,heavy physical work", Ex:"力仕事をする/do heavy lifting" },
  "神経": { Pron:"しんけい", Mean:"nerve", Ex:"神経が張り詰めた状態/nervous state" },
  "場合": { Pron:"ばあい", Mean:"case,instance", Ex:"場合によっては,in some cases" },
  "確認": { Pron:"かくにん", Mean:"make sure,confirm,check", Ex:"～かどうかを確認する/check whether (or not)" },
  "休": { Pron:"やす（む）", Mean:"get rest", Ex:"休む暇が全くない,not have any time to rest" },
  "来": { Pron:"き（て）", Mean:"come", Ex:"来て見る/come and see,来てください/please come" },
  "持": { Pron:"も（つ）", Mean:"hold,carry", Ex:"重い物を持つ/lift heavy objects,彼女はバッグを持っています/She is holding a bag" },
  "受": { Pron:"う（ける）", Mean:"get,take", Ex:"あなたのメールを受け取りました/I got your email" },
  "服用": { Pron:"ふくよう", Mean:"take medicine / use medication", Ex:"彼女はぜんそくの薬を使用しています/She uses medication for asthma" },
  "急": { Pron:"きゅう（に）", Mean:"suddenly", Ex:"急に雨が降り始めた/It suddenly started raining" },
  "月後": { Pron:"（いっか）げつご", Mean:"one month later", Ex:"彼は1か月後に戻ってきた/One month later he returned" },
  "避": { Pron:"さ（ける）", Mean:"avoid/do't do", Ex:"激しい運動は避けてください/Please avoid strenuous exercise" },
};
